---
# Source: address-check-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-check-address-check-application
  labels:
    helm.sh/chart: address-check-application-1.1.2
    app.kubernetes.io/name: address-check-application
    app.kubernetes.io/instance: address-check
    app.kubernetes.io/version: "1.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: address-check-application
      app.kubernetes.io/instance: address-check
  template:
    metadata:
      labels:
        app.kubernetes.io/name: address-check-application
        app.kubernetes.io/instance: address-check
    spec:
      serviceAccountName: address-check-address-check-application
      securityContext:
        {}
      containers:
        - name: address-check-application
          securityContext:
            {}
          image: "k3d-fsm-akka.registry:5555/fsmakka/address-check-application:1.1.2"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: JDK_JAVA_OPTIONS
              value: "-XshowSettings:vm -XX:+AlwaysActAsServerClassMachine -XX:TieredStopAtLevel=1 -noverify"
