---
# Source: address-check-application/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: address-check-address-check-application
  labels:
    helm.sh/chart: address-check-application-1.1.2
    app.kubernetes.io/name: address-check-application
    app.kubernetes.io/instance: address-check
    app.kubernetes.io/version: "1.1.2"
    app.kubernetes.io/managed-by: Helm
