trigger: none

parameters:
  - name: sourceRepo
    type: string
  - name: branchName
    type: string

steps:
  - pwsh: |
      echo 'Hello from repo: ${{.parameters.sourceRepo }} @ ${{.parameters.branchName }}'