name: Prepare Service for new Environment
trigger: none

parameters:
  - name: branchName
    type: string
  - name: tag
    type: string
  - name: version
    type: string

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES

jobs:
  - job: CreateBranch
    displayName: Create Branch
    steps:
      - checkout: self
        clean: true
        fetchDepth: 0
        persistCredentials: true
      - script: |
          git fetch --all
          git config --global user.email "$(Build.RequestedForEmail)"
          git config --global user.name "$(Build.RequestedFor)"
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
        displayName: Git Create Branch
        env:
          BRANCH_NAME: ${{ parameters.branchName }}
      - task: DeleteFiles@1
        displayName: Clearing gitops directories
        inputs:
          SourceFolder: ./gitops/fsmakka
          Contents: "**/*"
      - bash: |
          curl -L https://github.com/helmfile/helmfile/releases/download/v0.150.0/helmfile_0.150.0_linux_amd64.tar.gz > helmfile.tar.gz
          tar -xvf helmfile.tar.gz
          chmod +x helmfile
          git fetch --all
          git checkout -b $BRANCH_NAME
          git config --global user.email "$(Build.RequestedForEmail)"
          git config --global user.name "$(Build.RequestedFor)"
          git add ./gitops/fsmakka/\*
          git commit -a -m "$TAG"
          git push -u origin $BRANCH_NAME
          git push origin "$TAG" --force
          ./helmfile template --state-values-set username=$(HELM_USER) --state-values-set password=$(HELM_PASSWORD) --state-values-set version=$VERSION --output-dir-template ./gitops/fsmakka
        displayName: Helmfile Execution / Git Commit / Tag
        env:
          BRANCH_NAME: ${{ parameters.branchName }}
          TAG: ${{ parameters.tag }}
          VERSION: ${{ parameters.version }}