trigger: none

jobs:
  - job: helmfile
    steps:
        - pwsh: |
            curl -L https://github.com/helmfile/helmfile/releases/download/v0.150.0/helmfile_linux_amd64 > helmfile
            chmod +x helmfile
            helmfile --version

