trigger: none

jobs:
  - job: helmfile
    steps:
        - bash: |
            curl -L https://github.com/helmfile/helmfile/releases/download/v0.150.0/helmfile_0.150.0_linux_amd64.tar.gz > helmfile.tar.gz
            tar -xvf helmfile.tar.gz
            ls -al
            chmod +x helmfile
            ./helmfile --version


