name: Prepare Environment

parameters:
  - name: sourceRepo
    type: string
  - name: version
    type: string

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES

jobs:
  - job: helmfile
    variables:
      - name: source-repo
        value: ${{ parameters.sourceRepo }}
      - name: version
        value: ${{ parameters.version }}
    steps:
        - checkout: self
          clean: true
          persistCredentials: true
        - task: DeleteFiles@1
          displayName: Clearing gitops directories
          inputs:
            SourceFolder: ./gitops/fsmakka
            Contents: "**/*"
        - bash: |
            curl -L https://github.com/helmfile/helmfile/releases/download/v0.150.0/helmfile_0.150.0_linux_amd64.tar.gz > helmfile.tar.gz
            tar -xvf helmfile.tar.gz
            ls -al
            chmod +x helmfile
            ./helmfile template --state-values-set username=$(HELM_USER) --state-values-set password=$(HELM_PASSWORD) --output-dir-template ./gitops/fsmakka
          displayName: Helmfile Execution
        - script: |
            git fetch --all
            git switch $(basename $(Build.SourceBranch))
            git config --global user.email "$(Build.RequestedForEmail)"
            git config --global user.name "$(Build.RequestedFor)"
            git add ./gitops/fsmakka/\*
            git commit -a -m "$SOURCE_REPO-$VERSION"
            git tag "$SOURCE_REPO-$(version)" --force
            git push origin "$SOURCE_REPO-$VERSION" -- force
          displayName: Git Tag
          env:
            SOURCE_REPO: $(source-repo)
            VERSION: $(version)
          


