stages:
  - deploy

variables:
  CI_IMAGE_VERSION: v17.36.0

process-helm:
  stage: deploy
  image: "${CI_REGISTRY}/gitlab-com/gl-infra/k8s-workloads/common/k8-helm-ci:${CI_IMAGE_VERSION}"
  before_script:
    - |
      git config --global user.name "Mehmet Salgar"
      git config --global user.email "salgarm@gmx.de"
      git config --global pull.rebase false
      git config --global pull.rebase true
      git config --global pull.ff only
  script:
    - |
      export
      mkdir workdir
      cd workdir
      git clone https://github.com/mehmetsalgar/fsm-akka-dev-environment.git
      git remote set-url origin "https://mehmetsalgar:${GITHUB_TOKEN}@github.com/mehmetsalgar/fsm-akka-dev-environment.git"
      git remote -v
      git fetch --all
      git pull origin development
      git checkout development
      rm -rf ./gitops/gitlab/fsmakka/*
      cd fsm-akka-dev-environment
      pwd
      cat default.yaml
      helmfile template --state-values-set username=$HELM_USER --state-values-set password=$HELM_PASSWORD --state-values-set url=$HELM_URL --state-values-set path=$HELM_PATH --output-dir-template ./gitops/gitlab/fsmakka
      git add ./gitops/gitlab/fsmakka/\*
      git commit -a -m "Helm Template for GKE"
      git push -u origin development
