stages:
  - deploy

variables:
  CI_IMAGE_VERSION: v17.36.0

process_helm:
  stage: deploy
  image: "${CI_REGISTRY}/gitlab-com/gl-infra/k8s-workloads/common/k8-helm-ci:${CI_IMAGE_VERSION}"
  script:
    - |
      export
      helmfile template --state-values-set username=$(HELM_USER) --state-values-set password=$(HELM_PASSWORD) --output-dir-template ./gitops/gitlab/fsmakka
