repositories:
  - name: fsm-akka
    url: europe-west3-docker.pkg.dev/fsmakka/fsm-akka-helm-ar
    username: {{ .StateValues.username }}
    password: {{ .StateValues.password }}
    oci: true

environments:
  default:
    values:
      - default.yaml

releases:
  - name: foureyes
    namespace: fsmakka
    #chart: oci://fsmakka.azurecr.io/helm/fsm-akka-helm-umbrella-chart-az
    chart: oci://europe-west3-docker.pkg.dev/fsmakka/fsm-akka-helm-ar/fsm-akka-helm-umbrella-chart-gitlab
    version: {{ .StateValues.version }}
    values:
      - values-dev.yaml