repositories:
  - name: fsm-akka
    url: http://fsmakka.salgar.org/repository/fsm-akka-helm/

releases:
  - name: foureyes
    namespace: fsmakka
    chart: fsm-akka/fsm-akka
    values:
      - values.yaml