environments:
  default:
    values:
      - environments/default/values.yaml

---

repositories:
  - name: fsm-akka
    url: {{ .StateValues.url }}
    username: {{ .StateValues.username }}
    password: {{ .StateValues.pswd }}
    oci: true

releases:
  - name: foureyes
    namespace: fsmakka
    #chart: oci://fsmakka.azurecr.io/helm/fsm-akka-helm-umbrella-chart
    chart: oci://{{ .StateValues.url }}{{ .StateValues.path }}
    version: {{ .StateValues.version }}
    values:
      - values-dev.yaml