repositories:
  - name: fsm-akka
    url: {{ .StateValues.url }}
    username: {{ .StateValues.username }}
    password: {{ env "HELM_PASSWORD" }}
    oci: true

environments:
  default:
    values:
      - default.yaml

releases:
  - name: foureyes
    namespace: fsmakka
    #chart: oci://fsmakka.azurecr.io/helm/fsm-akka-helm-umbrella-chart-az
    chart: oci://{{ .StateValues.url }}/{{ .StateValues.path }}
    version: {{ .StateValues.version }}
    values:
      - values-dev.yaml