repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

environments:
  default:
    values:
      - default.yaml

releases:
  - name: es
    namespace: elasticsearch
    chart: bitnami/elasticsearch
    version: {{ .StateValues.version }}
    values:
      - ./values.yaml
