repositories:
  - name: fsm-akka
    url: oci://fsmakka.azurecr.io/helm
    username: {{ .StateValues.username }}
    password: {{ .StateValues.password }}

environments:
  default:
    values:
      - default.yaml

releases:
  - name: foureyes
    namespace: fsmakka
    chart: fsm-akka/fsm-akka-helm-umbrella-chart-az
    version: {{ .StateValues.version }}
    values:
      - values-dev.yaml