repositories:
  - name: fsm-akka
    url: oci://fsmakka.azurecr.io/helm

releases:
  - name: foureyes
    namespace: fsmakka
    chart: fsm-akka/fsm-akka-helm-umbrella-chart-az
    version: {{ .StateValues.version }}
    values:
      - values-dev.yaml