repositories:
  - name: fsm-akka
    url: http://fsmakka.salgar.org/repository/fsm-akka-helm/

releases:
  - name: address-check
    namespace: fsmakka
    chart: fsm-akka/address-check-application
    version: 1.1.2
    values:
      - values-address-check.yaml
  - name: credit-score
    namespace: fsmakka
    chart: fsm-akka/credit-score-application
    version: 1.1.8
  - name: fraud-prevention
    namespace: fsmakka
    chart: fsm-akka/fraud-prevention-application
    version: 1.2.10
  - name: customer-relationship-adapter
    namespace: fsmakka
    chart: fsm-akka/customer-relationship-adapter-application
    version: 1.1.6
  - name: foureyes
    namespace: fsmakka
    chart: fsm-akka/fsm-akka-4eyes-application
    version: 1.0.2
    values:
      - values-fsm-akka-4eyes.yaml