repositories:
  - name: fsm-akka
    url: fsmakka.azurecr.io
    username: {{ .StateValues.username }}
    password: {{ .StateValues.password }}
    oci: true

environments:
  default:
    values:
      - default.yaml

releases:
  - name: foureyes
    namespace: fsmakka
    chart: oci://{{ .StateValues.url }}/{{ .StateValues.path }}
    version: {{ .StateValues.version }}
    values:
      - values-dev.yaml