---
# Source: fsm-akka-helm-umbrella-chart-az/charts/fraud-prevention-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foureyes-fraud-prevention-application
  labels:
    helm.sh/chart: fraud-prevention-application-1.2.0-alpha.99
    app.kubernetes.io/name: fraud-prevention-application
    app.kubernetes.io/instance: foureyes
    app.kubernetes.io/version: "1.2.0-alpha.99"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fraud-prevention-application
      app.kubernetes.io/instance: foureyes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fraud-prevention-application
        app.kubernetes.io/instance: foureyes
    spec:
      serviceAccountName: foureyes-fraud-prevention-application
      securityContext:
        {}
      containers:
        - name: fraud-prevention-application
          securityContext:
            {}
          image: "fsmakka.azurecr.io/fsmakka/fraud-prevention-application:1.2.0-alpha.99"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: JDK_JAVA_OPTIONS
              value: "-XshowSettings:vm -XX:+AlwaysActAsServerClassMachine -XX:TieredStopAtLevel=1 -noverify"
