---
# Source: fsm-akka-helm-umbrella-chart-gitlab/charts/credit-score-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foureyes-credit-score-application
  labels:
    helm.sh/chart: credit-score-application-0.1.0-usecase2.1
    app.kubernetes.io/name: credit-score-application
    app.kubernetes.io/instance: foureyes
    app.kubernetes.io/version: "0.1.0-usecase2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-score-application
      app.kubernetes.io/instance: foureyes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-score-application
        app.kubernetes.io/instance: foureyes
    spec:
      serviceAccountName: foureyes-credit-score-application
      securityContext:
        {}
      containers:
        - name: credit-score-application
          securityContext:
            {}
          image: "europe-west3-docker.pkg.dev/fsmakka/fsmakka-ar/credit-score-application:0.1.0-usecase2.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 5Mi
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: 1Mi
              memory: 256Mi
          env:
            - name: JDK_JAVA_OPTIONS
              value: "-XshowSettings:vm -XX:+AlwaysActAsServerClassMachine -XX:TieredStopAtLevel=1 -noverify"
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
