---
# Source: fsm-akka/charts/customer-relationship-adapter-application/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foureyes-customer-relationship-adapter-application
  labels:
    helm.sh/chart: customer-relationship-adapter-application-1.1.6
    app.kubernetes.io/name: customer-relationship-adapter-application
    app.kubernetes.io/instance: foureyes
    app.kubernetes.io/version: "1.1.6"
    app.kubernetes.io/managed-by: Helm
