---
# Source: fsm-akka-helm-umbrella-chart/charts/address-check-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foureyes-address-check-application
  labels:
    helm.sh/chart: address-check-application-1.4.0-alpha.144
    app.kubernetes.io/name: address-check-application
    app.kubernetes.io/instance: foureyes
    app.kubernetes.io/version: "1.4.0-alpha.144-development"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: address-check-application
      app.kubernetes.io/instance: foureyes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: address-check-application
        app.kubernetes.io/instance: foureyes
    spec:
      serviceAccountName: foureyes-address-check-application
      securityContext:
        {}
      containers:
        - name: address-check-application
          securityContext:
            {}
          image: "europe-west3-docker.pkg.dev/fsmakka/fsmakka-ar/address-check-application:1.4.0-alpha.144"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: JDK_JAVA_OPTIONS
              value: "-XshowSettings:vm -XX:+AlwaysActAsServerClassMachine -XX:TieredStopAtLevel=1 -noverify"
