---
# Source: fsm-akka/charts/fsm-akka-4eyes-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsm-akka-foureyes
  labels:
    helm.sh/chart: fsm-akka-4eyes-application-1.0.2
    app.kubernetes.io/name: foureyes
    app.kubernetes.io/instance: fsm-akka
    app.kubernetes.io/version: "1.0.2"
    app.kubernetes.io/managed-by: Helm
  namespace: fsmakka
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: foureyes
      app.kubernetes.io/instance: fsm-akka
      app: fsm-akka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foureyes
        app.kubernetes.io/instance: fsm-akka
        app: fsm-akka
    spec:
      serviceAccountName: fsm-akka-foureyes
      securityContext:
        {}
      containers:
        - name: fsm-akka-4eyes-application
          securityContext:
            {}
          image: "k3d-fsm-akka.registry:5555/fsmakka/fsm-akka-4eyes-application:1.0.2"
          imagePullPolicy: Always
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8787
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            initialDelaySeconds: 120
            periodSeconds: 30
          env:
            - name: KUBERNETES_NAMESPACE
              value: fsmakka
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: CASSANDRA_CONTACT_POINT
              value: "fsm-cassandra-dc1-all-pods-service.fsmakka.svc.cluster.local"
            - name: NUMBER_OF_SHARDS
              value: "30"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "fsm-akka-kafka-headless:9092"
            - name: K8SSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fsm-cassandra-superuser
                  key: password
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 512Mi
