---
# Source: fsm-akka-helm-umbrella-chart/charts/fraud-prevention-application/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foureyes-fraud-prevention-application
  labels:
    helm.sh/chart: fraud-prevention-application-1.4.0-usecase-gh-2.1
    app.kubernetes.io/name: fraud-prevention-application
    app.kubernetes.io/instance: foureyes
    app.kubernetes.io/version: "1.4.0-usecase-gh-2.1"
    app.kubernetes.io/managed-by: Helm
