name: Create Branch
run-name: Creating Branch triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        required: true
        type: string
      base-branch-name:
        required: true
        type: string
jobs:
  create:
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/create-branch.yaml@master
    with:
      branch-name: ${{ inputs.branch-name }}
      base-branch-name: ${{ inputs.base-branch-name }}
    secrets: inherit
