name: Prepare Environment
run-name: Preparing Environment for Development for Repo ${{ inputs.repo }} - Version ${{ inputs.version }} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      source-repo:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'bitnami'
          fetch-depth: 0
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./gitops/fsmakka/
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
      - name: DoTemplate
        run: |
          echo 'Deploy Umbrella Chart for Service Pipeline'
          helmfile --version
          helm version
          helmfile template --output-dir-template ./gitops/fsmakka
          echo $(date +%F_%T) > ./gitops/fsmakka/create_helm_templates.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: './gitops/fsmakka/'
          message: 'Created Manifests for ${{ inputs.source-repo }}-${{ inputs.version }}'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          tag: '${{ inputs.source-repo }}-${{ inputs.version }} --force'
          tag_push: '--force'