name: Prepare Environment
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
      - name: DoTemplate
        run: |
          echo 'Deploy Umbrella Chart for Service Pipeline'
          helmfile --version
          #helmfile template --output-dir-template $(pwd)/gitops/fsmakka
          echo date +%F_%T > ./gitops/fsmakka/fsm-akka/charts/fsm-akka-4eyes-application/create_helm_templates.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: './gitops/fsmakka/fsm-akka/charts/fsm-akka-4eyes-application'
          message: 'Created Manifests'
          committer_name: GitHub Actions
          committer_email: actions@github.com