name: Prepare Services Environment
run-name: Preparing Environment for Tag ${{ inputs.tag }} - Version ${{ inputs.version }} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  prepare:
    name: Preparing Services Environment
    runs-on: ubuntu-latest
    env:
      HELM_URL: ${{ secrets.HELM_URL }}
      HELM_PATH: ${{ secrets.HELM_PATH }}
      HELM_USER: ${{ secrets.HELM_USER }}
      HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
      UMBRELLA_CHART_VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.workflow_run.head_branch }}'
          fetch-depth: 0
      - name: Display Branch
        run: |
          echo "Branch: ${{ github.ref }}"
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./gitops/github/fsmakka/
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: "v0.153.1"
          helm-version: "v3.12.0"
      - name: DoTemplate
        shell: bash
        run: |
          echo 'Deploy Umbrella Chart for Service Pipeline'
          helmfile template -e default --state-values-set username=$HELM_USER  --state-values-set pswd=$HELM_PASSWORD --state-values-set url=$HELM_URL --state-values-set path=$HELM_PATH --state-values-set version=$UMBRELLA_CHART_VERSION --output-dir-template ./gitops/github/fsmakka
          echo $(date +%F_%T) > ./gitops/github/fsmakka/create_helm_templates.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: './gitops/github/fsmakka/'
          message: 'Created Manifests for ${{ inputs.tag}}'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          tag: '${{ inputs.tag }} --force'
          tag_push: '--force'