name: Prepare Services Environment
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  prepare:
    name: Preparing Services Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.workflow_run.head_branch }}'
          fetch-depth: 0
      - name: Display Branch
        run: |
          echo "Branch: ${{ github.ref }}"
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./gitops/fsmakka/
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
      - name: DoTemplate
        run: |
          echo 'Deploy Umbrella Chart for Service Pipeline'
          helmfile --version
          helmfile template --state-values-set version=19.5.2 --output-dir-template ./gitops/fsmakka
          echo $(date +%F_%T) > ./gitops/fsmakka/create_helm_templates.txt
          echo 'Version: "${{ inputs.version }}"'
      - uses: EndBug/add-and-commit@v9
        with:
          add: './gitops/fsmakka/'
          message: 'Created Manifests for ${{ inputs.tag}}'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          tag: '${{ inputs.tag }} --force'
          tag_push: '--force'